export const ADMIN_SUBMIT_REQUEST = "ADMIN_SUBMIT_REQUEST";
export const ADMIN_SUBMIT_SUCCESS = "ADMIN_SUBMIT_SUCCESS";
export const ADMIN_SUBMIT_FAILURE = "ADMIN_SUBMIT_FAILURE";

export const UPDATE_SUBMIT_REQUEST = "UPDATE_SUBMIT_REQUEST";
export const UPDATE_SUBMIT_SUCCESS = "UPDATE_SUBMIT_SUCCESS";
export const UPDATE_SUBMIT_FAILURE = "UPDATE_SUBMIT_FAILURE";
