export const EMPLOYEE_SUBMIT_REQUEST = "EMPLOYEE_SUBMIT_REQUEST";
export const EMPLOYEE_SUBMIT_SUCCESS = "EMPLOYEE_SUBMIT_SUCCESS";
export const EMPLOYEE_SUBMIT_FAILURE = "EMPLOYEE_SUBMIT_FAILURE";
